### ISSUE TITLE
Question about the DCR privacy metric

### ISSUE THREAD

**Issue by amad-person** [schneiderkamplab/syntheval#8]
Hello! Firstly, thank you for creating this wonderful library! 

I had a question regarding the DCR privacy metric implementation. 

In your [paper](https://arxiv.org/pdf/2404.15821v1) and [code](https://github.com/schneiderkamplab/syntheval/blob/7fdb9a1eff22ab8ded06b37ff68ff59058f7feee/src/syntheval/metrics/privacy/metric_distance_closest_record.py#L38), you compare the median DCR of (synthetic, train) and (train, train) distances. 

I was wondering if you considered comparing the median DCR of (synthetic, train) and (holdout, train)? I have usually seen this version (page 4 in [ref](https://arxiv.org/pdf/2312.05114)), and I was wondering if you had any insights into why (train, train) was used. 

I am using the DCR metric in a project and wanted to know if a holdout dataset should be used or not.

**Comment by notna07** [comment]
Hi! Thank you for your appreciation of what we are doing!

Yes. As we mention in our [paper](https://arxiv.org/pdf/2404.15821v1) the metric has a wealth of slightly different implementations in the literature, e.g. [Fan et al.](https://arxiv.org/abs/2008.12763), use avg(dist(train, synth)) - and [Ooko et al.](https://ieeexplore.ieee.org/document/9629420) use some form of 5th percentile dist(test, train) compared with dist(synth, train). The [paper you mention](https://arxiv.org/pdf/2312.05114) uses a similar comparison but with 5th percentile of dist(train, synth) vs. dist(train, test).

In the version currently implemented in our code we use median(dist(synth, train))/median(dist(train,train)), _which is not something we have seen elsewhere in the literature_. Back when we implemented this metric we experimented with the different ideas mentioned above but encountered some drawbacks that ultimately landed us on this version.

In particular: 
- Using avg(dist(train, synth)) even on normalised data returns an unbounded number which does not carry a lot of information. I.e. it does not tell you if the violation is serious or not, because we have nothing to compare with.
- Turning the above number into a fraction of the avg(dist(train, synth))/avg(dist(train,train)) or avg(dist(train, synth)/dist(train,train)) sometimes causes the DCR value to explode or vanish (e.g. if training samples are too similar).
- Putting a hard pass criterion like the 5th percentile of dist(train, synth) vs. dist(train, test), is something we wished to avoid since privacy is not an absolute property of synthetic data. Consider what happens up until, and crossing the criterion: would you say that the data goes from totally unsafe to totally safe at any particular point near this threshold?

The reason we end up using dist(train,train) in the denominator is to assess how the dist(synth,train) is in comparison to the real data's inherent compactness. If synthetic samples are further away from the real records than the records are amongst themselves we get a number above one - and on the converse a number below one.

That said, we wouldn't recommend relying on metrics such as DCR or NNDR, as the paper you mentioned demonstrates these metrics tend to underestimate privacy risks. We include them in the current version of SynthEval because they are widely used, not because they are the best metrics out there.

**Comment by amad-person** [comment]
Thank you so much for the detailed response!
